#!/bin/env bash
#######################################################################################
#                                                                                     #
#       A script to install a mainline version of NGINX with custombuild2             #
#       A version number of NGINX mainline is taken from NGINX's trac site            #
#                                                                                     #
#######################################################################################
#                                                                                     #
#            Version: 0.2 (Mon Aug  8 15:17:32 +07 2016)                              #
#            Written by: Alex S Grebenschikov (zEitEr)                                #
#            Site: www.poralix.com  E-mail: support@poralix.com                       #
#                                                                                     #
#######################################################################################
#######################################################################################
##                                                                                    #
##   MIT License                                                                      #
##                                                                                    #
##   Copyright (c) 2016 Alex S Grebenschikov (www.poralix.com)                        #
##                                                                                    #
##   Permission is hereby granted, free of charge, to any person obtaining a copy     #
##   of this software and associated documentation files (the "Software"), to deal    #
##   in the Software without restriction, including without limitation the rights     #
##   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell        #
##   copies of the Software, and to permit persons to whom the Software is            #
##   furnished to do so, subject to the following conditions:                         #
##                                                                                    #
##   The above copyright notice and this permission notice shall be included in all   #
##   copies or substantial portions of the Software.                                  #
##                                                                                    #
##   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR       #
##   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,         #
##   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE      #
##   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER           #
##   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,    #
##   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE    #
##   SOFTWARE.                                                                        #
##                                                                                    #
#######################################################################################

function usage()
{

    echo "########################################################################";
    echo "#                                                                      #";
    echo "#  A script to install a mainline version of NGINX with custombuild2   #";
    echo "#  A version number of NGINX mainline is taken from NGINX's trac site  #";
    echo "#            Version: 0.2 (Mon Aug  8 15:17:32 +07 2016)               #";
    echo "#            Written by: Alex S Grebenschikov (zEitEr)                 #";
    echo "#                                                                      #";
    echo "########################################################################";
    echo "";
    echo "Usage:";
    echo "   $0 versions - to update information of available mainline version ";
    echo "   $0 install  - to download and install the latest mainline version";
}

function update_version()
{
    TRAC_FILE="https://trac.nginx.org/nginx/export/HEAD/nginx/.hgtags";
    NGINX_INSTALLED_VER=`nginx -v 2>&1 | cut -d\/ -f2`;
    NGINX_VER=`wget -q ${TRAC_FILE} -O - | tail -1 | cut -d\- -f2`;
    cd /usr/local/directadmin/custombuild;
    cat custom_versions.txt | grep -Ev "^nginx:|^$" > custom_versions.txt.new;
    mv -f custom_versions.txt.new custom_versions.txt;
    echo "nginx:${NGINX_VER}:" >> custom_versions.txt;
}

function show_versions()
{
    echo "Latest mainline version of Nginx: ${NGINX_VER}";
    echo "Installed version of Nginx: ${NGINX_INSTALLED_VER}";
}

function download_nginx()
{
    cd /usr/local/directadmin/custombuild;
    wget http://nginx.org/download/nginx-${NGINX_VER}.tar.gz -O nginx-${NGINX_VER}.tar.gz;
}

function install_nginx()
{
    ./build update;
    ./build nginx;
}

case "$1" in
    "download")
        update_version;
        download_nginx;
        ;;
    "cron")
        update_version >/dev/null 2>&1;
        download_nginx >/dev/null 2>&1;
        ;;
    "versions")
        update_version;
        show_versions;
        ;;
    "install")
        update_version;
        download_nginx;
        install_nginx;
        ;;
    *)
        usage;
        ;;
esac;

exit 0;
